# version: '3'
# services:
#   app:
#     build: .
#     ports:
#       - "8080:8080"
#     volumes:
#       - ./public:/root/public  
#     container_name: my-python-server

version: '3.3'
services:
    app:
        build: .
        ports:
            - '8080:8080'
